-- MySQL Script generated by MySQL Workbench
-- lun. 17 oct. 2016 14:42:43 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app_compta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_compta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_compta` DEFAULT CHARACTER SET utf8 ;
USE `app_compta` ;

-- -----------------------------------------------------
-- Table `app_compta`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_compta`.`users` ;

CREATE TABLE IF NOT EXISTS `app_compta`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `pwd` VARCHAR(400) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_compta`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_compta`.`user_group` ;

CREATE TABLE IF NOT EXISTS `app_compta`.`user_group` (
  `id_user_group` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_compta`.`users_has_user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_compta`.`users_has_user_group` ;

CREATE TABLE IF NOT EXISTS `app_compta`.`users_has_user_group` (
  `id_users` INT NOT NULL,
  `id_user_group` INT NOT NULL,
  PRIMARY KEY (`id_users`, `id_user_group`),
  INDEX `fk_users_has_user_group_user_group1_idx` (`id_user_group` ASC),
  INDEX `fk_users_has_user_group_users_idx` (`id_users` ASC),
  CONSTRAINT `fk_users_has_user_group_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `app_compta`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_user_group_user_group1`
    FOREIGN KEY (`id_user_group`)
    REFERENCES `app_compta`.`user_group` (`id_user_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_compta`.`depenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_compta`.`depenses` ;

CREATE TABLE IF NOT EXISTS `app_compta`.`depenses` (
  `id_depenses` INT NOT NULL AUTO_INCREMENT,
  `montant` FLOAT NULL,
  `date` DATE NULL,
  `description` VARCHAR(300) NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id_depenses`),
  INDEX `fk_depenses_users1_idx` (`id_users` ASC),
  CONSTRAINT `fk_depenses_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `app_compta`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_compta`.`concernes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_compta`.`concernes` ;

CREATE TABLE IF NOT EXISTS `app_compta`.`concernes` (
  `id_depenses` INT NOT NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id_depenses`, `id_users`),
  INDEX `fk_depenses_has_users_users1_idx` (`id_users` ASC),
  INDEX `fk_depenses_has_users_depenses1_idx` (`id_depenses` ASC),
  CONSTRAINT `fk_depenses_has_users_depenses1`
    FOREIGN KEY (`id_depenses`)
    REFERENCES `app_compta`.`depenses` (`id_depenses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_depenses_has_users_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `app_compta`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
